const DATA = [
  {
    id: 0,
    title: "BESITOS GLOSS DRIP",
    price: 75,
    desc: "Swipe on my new, limited-edition Gloss Drip for a juicy and reflective, mirror-shine finish. Featuring a cushiony texture, it’s comfortable to wear, softens lips, and provides a wet look without stickiness. The shade Besitos is a sheer watermelon pink gloss.",
    img: "/assets/images/products/rouge.jfif",
  },
  {
    id: 1,
    title: "PINK ME UP LIP & CHEEK GLOW BALM",
    price: 80,
    desc: "My limited-edition Lip & Cheek Glow Balm is for those that love a natural flush of color with a radiant, satin finish. This silky, weightless cream instantly melts into the skin while providing buildable color without cakiness or streaks. Wear it on your cheeks for a second-skin glow, or on your lips for a hint of color and sheen. Pink Me Up is a medium pink shade.",
    img: "/assets/images/products/fard.jfif",
  },
  {
    id: 2,
    title: "The Ultimate Lip Trio Set - Bombshell",
    price: 95,
    desc: "The Lip Trio is a love letter to one of Huda’s favorite lipsticks: Liquid Matte Liquid Lipstick in Bombshell. She even handpicked the perfect Lip Contour 2.0 Automatic Lip Pencil and Power Bullet Matte Lipstick to pair with the beloved pink-toned nude.",
    img: "/assets/images/products/set.jpg",
  },
  {
    id: 3,
    title: "Basic Besties",
    price: 20,
    desc: "Our BASIC BESTIES Bundle is a 3 pack of our cult favorite sponges in a bundle for you to store everywhere and every moment you might need it. Pairs perfectly with any HUDA BEAUTY complexion product! A double-sided sponge applicator designed for applying and blending all formulas to create a perfectly flawless complexion.",
    img: "/assets/images/products/basic.jfif",
  },
  {
    id: 4,
    title: "Lovefest Obsessions Eyeshadow Palette",
    price: 29,
    desc: "Major festival vibes! An easy-to-use, warm-toned eyeshadow palette packed with a variety of party-ready shades and textures, from velvety mattes in sunset hues to dazzling purple sequin-inspired shimmers.",
    img: "/assets/images/products/palette.jpg",
  },
  {
    id: 5,
    title: "FauxFilter Luminous Matte Foundation",
    price: 42,
    desc: "FauxFilter is back with the same full coverage and long-lasting properties, you know and love from the OG formula, but with 24-hour flexible wear, a luminous matte finish AND… it’s fragrance-free! The true filter effect gives instant coverage so seamless that it immediately unifies skin tone and texture as it blurs skin to give a radiant finish. The non-cakey formula is life proof (waterproof, super long wear (24hr), transfer proof, fade proof, sweat proof, humidity proof.) No matter what the weather, occasion or situation, #FauxFilter Luminous Matte will NEVER let you down.",
    img: "/assets/images/products/foundation.jpg",
  },
  {
    id: 6,
    title: " GloWish Blur Jam Silicone-Free Smoothing Primer",
    price: 33,
    desc: "An instantly smoothing, mattifying, and breathable primer that is silicone-free and jam-packed with skin-loving ingredients for all-day hydration and12-hour pore-blurring power! Infused with Damascus rose water, prickly pear, and cactus flower extract, the formula helps to boost hydration, maintain skin barrier protection, and extend makeup wear for up to 12 hours! You can wear it under, alone, or on top of makeup for a shine-free, even complexion.",
    img: "/assets/images/products/primer.jpg",
  },
  {
    id: 7,
    title: " GloWish All Over Face Powder Brush",
    price: 31,
    desc: "A domed, plush powder brush that effortlessly glides across the face for an airbrushed application and a soft, smooth veil of color that won’t settle into your pores! Pairs perfectly with our GloWish Luminous Pressed Powder.",
    img: "/assets/images/products/brush.jpg",
  },
  {
    id: 8,
    title: "Honey Whip Peptide Moisturizer",
    price: 32.5,
    desc: "Loaded with powerful natural extracts & potent actives like manuka honey, cica, peptides and collagen, this rich-but-lightweight whipped cream moisturizer helps to firm, lift, repair, AND plump the skin, as well as reduce redness and even out your complexion. Honey Whip Peptide Moisturizer is also non-comedogenic & Dermatologist tested!",
    img: "/assets/images/topvente/soin1.jfif",
  },
  {
    id: 9,
    title: "Clean Genie Cleansing Butter",
    price: 80,
    desc: "Clean, Refreshed, and Radiant Skin! . A cleansing butter infused with green tea and cherry blossom extract to melt away makeup and impurities while keeping skin feeling soft and supple, instead of greasy and dry. ",
    img: "/assets/images/topvente/soin2.jfif",
  },
  {
    id: 10,
    title: " Get Even Rose Oil",
    price: 47.25,
    desc: "A skincare powerhouse, Get Even Rose Facial Oil is a blend of 15 exceptional oils chosen for their potent, skin-enhancing benefits. Nicknamed by Huda as her magic oil, this is a holy grail for all skin types, leaving you with a healthy-looking glow, a brighter appearance, and a visibly even texture.",
    img: "/assets/images/topvente/soin3.jpg",
  },
  {
    id: 11,
    title: "WISHFUL Rose Headband",
    price: 20,
    desc: "Complete your skincare & makeup routine with our super fluffy, soft & stretchy headband that will make your regimen more efficient (& SO much cuter!)",
    img: "/assets/images/topvente/soin4.jfif",
  },
];

export default DATA;
